//package model;
//
//import java.io.FileOutputStream;
//import java.text.SimpleDateFormat;
//import java.util.Date;
//import java.util.Calendar;
//import java.util.Locale;
//import java.io.FileOutputStream;
//import com.itextpdf.text.Image;
//import com.itextpdf.text.pdf.PdfContentByte;
//import com.itextpdf.text.pdf.PdfReader;
//import com.itextpdf.text.pdf.PdfStamper;
//import com.itextpdf.text.Anchor;
//import com.itextpdf.text.BaseColor;
//import com.itextpdf.text.Chapter;
//import com.itextpdf.text.Document;
//import com.itextpdf.text.Element;
//import com.itextpdf.text.Font;
//import com.itextpdf.text.Header;
//import com.itextpdf.text.Image;
//import com.itextpdf.text.Paragraph;
//import com.itextpdf.text.Phrase;
//import com.itextpdf.text.Section;
//import com.itextpdf.text.pdf.PdfPCell;
//import com.itextpdf.text.pdf.PdfPTable;
//import com.itextpdf.text.pdf.PdfWriter;
// 
//public class CriaNovoPDF {
// 
//	private static Font fonteCabecalho = new Font(Font.FontFamily.HELVETICA, 22, 
//			Font.UNDERLINE);
//	
//	private static Font fontePadrao = new Font(Font.FontFamily.HELVETICA, 14, Font.NORMAL);
//	private static Font negritoPequena = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD);
// //vermelho59 verde173 azul229
//	public static void main(String[] arq) {
//		try {
//			System.out.println("Início");
// 
//			// Criação do objeto que será um documento PDF
//			Document documento = new Document();
//			// Faz o apontamento para o arquivo de destino
//			PdfWriter.getInstance(documento, new FileOutputStream(
//					"D:/Timesheet_HR.pdf"));
//			// Realiza a abertura do arquivo para escrita
//			documento.open();
//			// Escreve uma mensagem no arquivo
//			
//			Image img = Image.getInstance("D://teste.png");		
//			img.setAlignment(Element.ALIGN_CENTER);			
//			documento.add(img);
//			
//			
//			
// 
//			// Adicionando meta dados ao nosso arquivo
//			documento.addTitle("Aqui está o título");
//			documento.addSubject("Agora temos um assunto no arquivo!");
//			documento.addKeywords("Java, PDF, iText");
//			documento.addAuthor("André Felix");
//			documento.addCreator("André Félix");
// 
//			Paragraph conteudo = new Paragraph();
//			// Assim criaremos uma linha em branco
//			conteudo.add(new Paragraph(" "));
// 
//			conteudo.add(new Paragraph("Relatório de Controle", fonteCabecalho));
//			conteudo.setAlignment(Element.ALIGN_CENTER);
//			
//			// Pular nova linha
//			conteudo.add(new Paragraph(" "));
// 
//			// Will create: Report generated by: _name, _date
//			Calendar cal = Calendar.getInstance();
//			conteudo.add(new Paragraph("Consultor: Fabiola Saito", negritoPequena));
//			conteudo.add(new Paragraph("Mês Referente: Maio/2016 ", negritoPequena));
//			conteudo.add(new Paragraph("Projetos: Hyundai", negritoPequena));
//			conteudo.add(new Paragraph("Relatório Gerado em: "
//					+ cal, negritoPequena));
//			
//			cal.set(Calendar.DAY_OF_MONTH, 0);
//			cal.set(Calendar.MONTH, 0);
//			cal.set(Calendar.YEAR, 0);
//			conteudo.add(new Paragraph(" ", negritoPequena));
//			conteudo.add(new Paragraph(" "));
//			
//			
//
//			// Criação de um apontamento para um capítulo
//			Anchor ancora = new Anchor("", fontePadrao);
//			ancora.setName("");
// 
//			// Capítulo do arquivo
//			
// 
//			Paragraph novoParagrafo = new Paragraph("",
//					negritoPequena);
// 
//			// Seção é uma área que adicionaremos conteúdo
//			
// 
//			// Tabela com 4 colunas
//			PdfPTable table = new PdfPTable(4);
// 
//			PdfPCell c1 = new PdfPCell(new Phrase("Data"));
//			c1.setHorizontalAlignment(Element.ALIGN_CENTER);
//			c1.setBackgroundColor(new BaseColor(128, 159, 255));
//			table.addCell(c1);
//			
// 
//			c1 = new PdfPCell(new Phrase("Projeto"));
//			c1.setHorizontalAlignment(Element.ALIGN_CENTER);
//			c1.setBackgroundColor(new BaseColor(128, 159, 255));
//			table.addCell(c1);
//			
// 
//			c1 = new PdfPCell(new Phrase("Horas Trabalhadas"));
//			c1.setHorizontalAlignment(Element.ALIGN_CENTER);
//			c1.setBackgroundColor(new BaseColor(128, 159, 255));
//			table.addCell(c1);
//			
//			
//			c1 = new PdfPCell(new Phrase("Total de Horas"));
//			c1.setHorizontalAlignment(Element.ALIGN_CENTER);
//			c1.setBackgroundColor(new BaseColor(128, 159, 255));
//			table.addCell(c1);
//			
//			table.setHeaderRows(1);
//			//Deixa centralizado os campos
//			table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
// 
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("01/04/2016");
//			table.addCell("Hyundai");
//			table.addCell("08:00");
//			table.addCell("");
//			table.addCell("");
//			table.addCell("");
//			table.addCell("");
//			table.addCell("400");
//			
//			
//			
//			
// 
//			// Serão criadas mais 10 células na tabela
//			// a ordem será da esquerda para a direita de criação
//			// ao final de cada linha uma nova célula será criada na próxima
//			// linha
//			documento.add(conteudo);
//			documento.add(table);
//			
//			
// 
//			// Fecha o arquivo após a escrita da mensagem
//			documento.close();
//			System.out.println("Fim");
//		} catch (Exception e) {
//			e.printStackTrace();
//		}
//	}
//
//	   
//	    }
//
//
